. /opt/homebrew/opt/asdf/libexec/asdf.sh
eval "$(/opt/homebrew/bin/brew shellenv)"

# git Aliases
alias gst='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias ga='git add'
alias gai='git add -i'
alias gbd='git branch -d'
alias gba='git branch -a'
alias gco='git checkout'
alias gl='git log'
alias gc='git commit'

# replace vim with nvim
# alias vim='nvim'
# alias v='nvim'
# alias vimdiff='nvim -d'
# export EDITOR=nvim

source ~/.zshrc-local
